[package]
name = "github-label-adder"
version = "0.1.0"
authors = ["Matt Farina <matt@mattfarina.com>"]
readme = "README.md"

[dependencies]
hubcaps = "^0.4.10"
tokio-core = "0.1"
log = "0.4.0"
env_logger = "0.5.12"
futures = "0.1"